// <auto-generated />
namespace EventsManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class EventsIdentityDb2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventsIdentityDb2));
        
        string IMigrationMetadata.Id
        {
            get { return "201701120156220_EventsIdentityDb2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
