//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Participants = new HashSet<Participant>();
        }
    
        public System.Guid event_id { get; set; }
        public string event_name { get; set; }
        public string event_location { get; set; }
        public System.DateTime start_datetime { get; set; }
        public System.DateTime end_datetime { get; set; }
        public byte[] event_banner { get; set; }
        public bool delete_flag { get; set; }
        public Nullable<System.DateTime> deleted_datetime { get; set; }
        public System.DateTime date_created { get; set; }
        public int passcode { get; set; }
        public string email_address { get; set; }
        public Nullable<bool> hasRaffle { get; set; }
        public Nullable<bool> registration_req { get; set; }
        public Nullable<int> participant_count { get; set; }
        public Nullable<bool> closed_flag { get; set; }
        public Nullable<System.DateTime> closed_datetime { get; set; }
        public Nullable<bool> reopen_flag { get; set; }
        public Nullable<System.DateTime> reopen_datetime { get; set; }
        public Nullable<short> registration_type { get; set; }
        public string created_by { get; set; }
    
        public virtual ICollection<Participant> Participants { get; set; }
    }
}
